declare module "*.jpeg"
declare module "*.jpg"
declare module "*.png"
declare module "*.module.css"
declare module "react-select-us-states"
declare module "react-credit-cards"
declare module "react-router-hash-link"